apiVersion: v1
kind: Service  # Define a 'Service' To Expose mysql to Other Services
metadata:
  name: mysql  # DNS name
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - protocol: TCP
      port: 3307
      targetPort: mysql-port
  selector:       # mysql Pod Should contain same labels
    app: mysql
    tier: database